### ISSUE TITLE
Could you plz help to up the /graphiql-online/ again

### ISSUE THREAD

**Issue by kimhue17** [lucasconstantino/graphiql-online#5]
I used this site to learn and practice about graphql, very helpful. But now when I access this site, I got error 'TypeError: Failed to fetch'. Could you please help to bring it up again? thank you!

**Comment by lucasconstantino** [comment]
Hello, @kimhue17. The issue is not with my project, but with the GraphQL I used as an example to connect to. You can still use this tool by changing the endpoint to a working GraphQL (top left corner).

You can find a list of open public GraphQL APIs here: https://github.com/APIs-guru/graphql-apis

Anyway, I'll try to update the default GraphQL API this tool is connected to, so to avoid the failure feeling.

**Comment by lucasconstantino** [comment]
Ps.: updated ;)
